// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{ffi, Annot, AnnotCalloutLine, AnnotFreeTextQuadding, AnnotMarkup};
use glib::translate::*;

glib::wrapper! {
    #[doc(alias = "PopplerAnnotFreeText")]
    pub struct AnnotFreeText(Object<ffi::PopplerAnnotFreeText>) @extends AnnotMarkup, Annot;

    match fn {
        type_ => || ffi::poppler_annot_free_text_get_type(),
    }
}

impl AnnotFreeText {
    #[doc(alias = "poppler_annot_free_text_get_callout_line")]
    #[doc(alias = "get_callout_line")]
    pub fn callout_line(&self) -> Option<AnnotCalloutLine> {
        unsafe {
            from_glib_full(ffi::poppler_annot_free_text_get_callout_line(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "poppler_annot_free_text_get_quadding")]
    #[doc(alias = "get_quadding")]
    pub fn quadding(&self) -> AnnotFreeTextQuadding {
        unsafe {
            from_glib(ffi::poppler_annot_free_text_get_quadding(
                self.to_glib_none().0,
            ))
        }
    }
}
