// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    pub struct Color(BoxedInline<ffi::PopplerColor>);

    match fn {
        copy => |ptr| ffi::poppler_color_copy(mut_override(ptr)),
        free => |ptr| ffi::poppler_color_free(ptr),
        type_ => || ffi::poppler_color_get_type(),
    }
}

impl Color {
    #[doc(alias = "poppler_color_new")]
    pub fn new() -> Color {
        unsafe { from_glib_full(ffi::poppler_color_new()) }
    }
}

impl Default for Color {
    fn default() -> Self {
        Self::new()
    }
}
