// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::GStr;

#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_CIRCLE")]
pub static ANNOT_TEXT_ICON_CIRCLE: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_CIRCLE) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_COMMENT")]
pub static ANNOT_TEXT_ICON_COMMENT: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_COMMENT) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_CROSS")]
pub static ANNOT_TEXT_ICON_CROSS: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_CROSS) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_HELP")]
pub static ANNOT_TEXT_ICON_HELP: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_HELP) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_INSERT")]
pub static ANNOT_TEXT_ICON_INSERT: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_INSERT) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_KEY")]
pub static ANNOT_TEXT_ICON_KEY: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_KEY) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_NEW_PARAGRAPH")]
pub static ANNOT_TEXT_ICON_NEW_PARAGRAPH: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_NEW_PARAGRAPH) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_NOTE")]
pub static ANNOT_TEXT_ICON_NOTE: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_NOTE) };
#[doc(alias = "POPPLER_ANNOT_TEXT_ICON_PARAGRAPH")]
pub static ANNOT_TEXT_ICON_PARAGRAPH: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::POPPLER_ANNOT_TEXT_ICON_PARAGRAPH) };
