// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Dest(Boxed<ffi::PopplerDest>);

    match fn {
        copy => |ptr| ffi::poppler_dest_copy(mut_override(ptr)),
        free => |ptr| ffi::poppler_dest_free(ptr),
        type_ => || ffi::poppler_dest_get_type(),
    }
}
