// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct ImageMapping(Boxed<ffi::PopplerImageMapping>);

    match fn {
        copy => |ptr| ffi::poppler_image_mapping_copy(mut_override(ptr)),
        free => |ptr| ffi::poppler_image_mapping_free(ptr),
        type_ => || ffi::poppler_image_mapping_get_type(),
    }
}

impl ImageMapping {
    #[doc(alias = "poppler_image_mapping_new")]
    pub fn new() -> ImageMapping {
        unsafe { from_glib_full(ffi::poppler_image_mapping_new()) }
    }
}

impl Default for ImageMapping {
    fn default() -> Self {
        Self::new()
    }
}
