// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod annot;
pub use self::annot::Annot;

mod annot_circle;
pub use self::annot_circle::AnnotCircle;

mod annot_file_attachment;
pub use self::annot_file_attachment::AnnotFileAttachment;

mod annot_free_text;
pub use self::annot_free_text::AnnotFreeText;

mod annot_markup;
pub use self::annot_markup::AnnotMarkup;

mod attachment;
pub use self::attachment::Attachment;

mod document;
pub use self::document::Document;

mod font_info;
pub use self::font_info::FontInfo;

mod form_field;
pub use self::form_field::FormField;

mod layer;
pub use self::layer::Layer;

mod media;
pub use self::media::Media;

mod movie;
pub use self::movie::Movie;

mod ps_file;
pub use self::ps_file::PSFile;

mod page;
pub use self::page::Page;

mod structure_element;
pub use self::structure_element::StructureElement;

mod annot_callout_line;
pub use self::annot_callout_line::AnnotCalloutLine;

mod annot_mapping;
pub use self::annot_mapping::AnnotMapping;

#[cfg(feature = "v23_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v23_7")))]
mod certificate_info;
#[cfg(feature = "v23_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v23_7")))]
pub use self::certificate_info::CertificateInfo;

mod color;
pub use self::color::Color;

mod dest;
pub use self::dest::Dest;

mod fonts_iter;
pub use self::fonts_iter::FontsIter;

mod form_field_mapping;
pub use self::form_field_mapping::FormFieldMapping;

mod image_mapping;
pub use self::image_mapping::ImageMapping;

mod index_iter;
pub use self::index_iter::IndexIter;

mod layers_iter;
pub use self::layers_iter::LayersIter;

mod link_mapping;
pub use self::link_mapping::LinkMapping;

mod page_transition;
pub use self::page_transition::PageTransition;

mod point;
pub use self::point::Point;

mod quadrilateral;
pub use self::quadrilateral::Quadrilateral;

mod rectangle;
pub use self::rectangle::Rectangle;

#[cfg(feature = "v21_12")]
#[cfg_attr(docsrs, doc(cfg(feature = "v21_12")))]
mod signature_info;
#[cfg(feature = "v21_12")]
#[cfg_attr(docsrs, doc(cfg(feature = "v21_12")))]
pub use self::signature_info::SignatureInfo;

#[cfg(feature = "v23_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v23_7")))]
mod signing_data;
#[cfg(feature = "v23_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v23_7")))]
pub use self::signing_data::SigningData;

mod structure_element_iter;
pub use self::structure_element_iter::StructureElementIter;

mod text_attributes;
pub use self::text_attributes::TextAttributes;

mod text_span;
pub use self::text_span::TextSpan;

mod enums;
pub use self::enums::ActionLayerAction;
pub use self::enums::ActionMovieOperation;
pub use self::enums::ActionType;
#[cfg(feature = "v0_72")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_72")))]
pub use self::enums::AdditionalActionType;
pub use self::enums::AnnotExternalDataType;
pub use self::enums::AnnotFreeTextQuadding;
pub use self::enums::AnnotMarkupReplyType;
pub use self::enums::AnnotTextState;
pub use self::enums::AnnotType;
pub use self::enums::Backend;
#[cfg(feature = "v21_12")]
#[cfg_attr(docsrs, doc(cfg(feature = "v21_12")))]
pub use self::enums::CertificateStatus;
pub use self::enums::DestType;
pub use self::enums::Error;
pub use self::enums::FontType;
pub use self::enums::FormButtonType;
pub use self::enums::FormChoiceType;
pub use self::enums::FormFieldType;
pub use self::enums::FormTextType;
pub use self::enums::MoviePlayMode;
pub use self::enums::PDFConformance;
pub use self::enums::PDFPart;
pub use self::enums::PDFSubtype;
pub use self::enums::PageLayout;
pub use self::enums::PageMode;
pub use self::enums::PageTransitionAlignment;
pub use self::enums::PageTransitionDirection;
pub use self::enums::PageTransitionType;
#[cfg(feature = "v0_80")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_80")))]
pub use self::enums::PrintDuplex;
#[cfg(feature = "v0_73")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_73")))]
pub use self::enums::PrintScaling;
pub use self::enums::SelectionStyle;
#[cfg(feature = "v21_12")]
#[cfg_attr(docsrs, doc(cfg(feature = "v21_12")))]
pub use self::enums::SignatureStatus;
pub use self::enums::StructureBlockAlign;
pub use self::enums::StructureBorderStyle;
pub use self::enums::StructureElementKind;
pub use self::enums::StructureFormRole;
pub use self::enums::StructureFormState;
pub use self::enums::StructureGlyphOrientation;
pub use self::enums::StructureInlineAlign;
pub use self::enums::StructureListNumbering;
pub use self::enums::StructurePlacement;
pub use self::enums::StructureRubyAlign;
pub use self::enums::StructureRubyPosition;
pub use self::enums::StructureTableScope;
pub use self::enums::StructureTextAlign;
pub use self::enums::StructureTextDecoration;
pub use self::enums::StructureWritingMode;

mod flags;
pub use self::flags::AnnotFlag;
pub use self::flags::FindFlags;
pub use self::flags::Permissions;
pub use self::flags::PrintFlags;
#[cfg(feature = "v21_12")]
#[cfg_attr(docsrs, doc(cfg(feature = "v21_12")))]
pub use self::flags::SignatureValidationFlags;
pub use self::flags::StructureGetTextFlags;
pub use self::flags::ViewerPreferences;

pub(crate) mod functions;

mod constants;
pub use self::constants::ANNOT_TEXT_ICON_CIRCLE;
pub use self::constants::ANNOT_TEXT_ICON_COMMENT;
pub use self::constants::ANNOT_TEXT_ICON_CROSS;
pub use self::constants::ANNOT_TEXT_ICON_HELP;
pub use self::constants::ANNOT_TEXT_ICON_INSERT;
pub use self::constants::ANNOT_TEXT_ICON_KEY;
pub use self::constants::ANNOT_TEXT_ICON_NEW_PARAGRAPH;
pub use self::constants::ANNOT_TEXT_ICON_NOTE;
pub use self::constants::ANNOT_TEXT_ICON_PARAGRAPH;

pub(crate) mod traits {
    pub use super::annot::AnnotExt;
    pub use super::annot_markup::AnnotMarkupExt;
    pub use super::attachment::AttachmentExt;
}
pub(crate) mod builders {
    pub use super::document::DocumentBuilder;
}
