// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct PageTransition(Boxed<ffi::PopplerPageTransition>);

    match fn {
        copy => |ptr| ffi::poppler_page_transition_copy(mut_override(ptr)),
        free => |ptr| ffi::poppler_page_transition_free(ptr),
        type_ => || ffi::poppler_page_transition_get_type(),
    }
}

impl PageTransition {
    #[doc(alias = "poppler_page_transition_new")]
    pub fn new() -> PageTransition {
        unsafe { from_glib_full(ffi::poppler_page_transition_new()) }
    }
}

impl Default for PageTransition {
    fn default() -> Self {
        Self::new()
    }
}
