// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::translate::*;

glib::wrapper! {
    pub struct Quadrilateral(BoxedInline<ffi::PopplerQuadrilateral>);

    match fn {
        copy => |ptr| ffi::poppler_quadrilateral_copy(mut_override(ptr)),
        free => |ptr| ffi::poppler_quadrilateral_free(ptr),
        type_ => || ffi::poppler_quadrilateral_get_type(),
    }
}

impl Quadrilateral {
    #[doc(alias = "poppler_quadrilateral_new")]
    pub fn new() -> Quadrilateral {
        unsafe { from_glib_full(ffi::poppler_quadrilateral_new()) }
    }
}

impl Default for Quadrilateral {
    fn default() -> Self {
        Self::new()
    }
}
